reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    - Melodic/Shared/Generated/

disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - force_cast
    - force_unwrapping
    - force_try
    - empty_enum_arguments
    - overridden_super_call
    - sorted_imports
    - vertical_whitespace
    - number_separator

opt_in_rules: # some rules are only opt-in
    - yoda_condition
    - empty_count
    - empty_string
    - closure_end_indentation
    - closure_spacing
    - explicit_init
    - first_where
    - explicit_failure_calls
    - fatal_error_message
    - vertical_parameter_alignment_on_call
    - multiline_parameters
    - nesting

    - private_outlet
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_nil_coalescing
    - syntactic_sugar
    - comments_space
    - conditional_returns_on_newline

conditional_returns_on_newline:
    if_only: true
    
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 4
    error: 6

type_name: # class name
    min_length: 3
    max_length:
        warning: 60
        error: 80

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 500
    error: 800
    ignore_comment_only_lines: true

identifier_name: # Variable name
    allowed_symbols: "_"
    min_length: 1
    max_length:
        warning: 60
        error: 80
    excluded:
        - id
        - URL
        - GlobalAPIKey

large_tuple:
    warning: 4
    error: 5

private_outlet:
    allow_private_set: true

#cyclomatic complexity below 4 is considered good;
#cyclomatic complexity between 5 and 7 is considered medium complexity,
#between 8 and 10 is high complexity,
#and above that is extreme complexity.
cyclomatic_complexity:
    ignores_case_statements: true
    warning: 7
    error: 11

custom_rules:
    comments_space: # From https://github.com/brandenr/swiftlintconfig
      name: "Space After Comment"
      regex: '(^ *//\w+)'
      message: "There should be a space after //"
      severity: warning
    explicit_failure_calls:
        name: “Avoid asserting ‘false’”
        regex: ‘((assert|precondition)\(false)’
        message: “Use assertionFailure() or preconditionFailure() instead.”
        severity: warning
    multiple_empty_lines:
       name: "Multiple Empty Lines"
       regex: '((?:\s*\n){3,})'
       message: "There are too many line breaks"
       severity: error

